services:
  - type: web
    name: telegram-tracker
    runtime: docker
    plan: free
    dockerfilePath: Dockerfile
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.6
      - key: FLASK_ENV
        value: production
